/**
 * Module: config
 * Purpose: Provide a single, frozen configuration object for the Enterprise PSEO engine core.
 * Responsibilities: Surface default values for build, cache, SEO, logging, and validation concerns
 * so downstream consumers share one source of truth.
 * Dependencies: None. This module deliberately imports no project files so it can be loaded from
 * any entry point without side effects or cycles.
 */

/**
 * Central configuration object.
 *
 * @type {Readonly<Record<string, unknown>>}
 */
export const config = Object.freeze({
  /**
   * Build-time concerns.
   *
   * @type {{outputDirectory: string, publicPath: string, assetPrefix: string, concurrency: number, minify: boolean, sourceMaps: boolean}}
   */
  build: Object.freeze({
    /** Directory where generated artifacts are written. */
    outputDirectory: 'dist',
    /** URL path prefix under which the site is served. */
    publicPath: '/',
    /** Prefix applied to static asset URLs. */
    assetPrefix: '/assets',
    /** Maximum number of pages rendered in parallel. */
    concurrency: 4,
    /** Whether to minify generated HTML and assets. */
    minify: true,
    /** Whether to emit source maps for generated assets. */
    sourceMaps: false,
  }),

  /**
   * Cache concerns.
   *
   * @type {{maxAgeMs: number, maxSize: number, staleWhileRevalidateMs: number, enabled: boolean}}
   */
  cache: Object.freeze({
    /** Default time-to-live for cached entries, in milliseconds. */
    maxAgeMs: 5 * 60 * 1000,
    /** Maximum number of entries retained in an in-memory cache. */
    maxSize: 1000,
    /** Window during which a stale cached entry may be served while a refresh runs, in milliseconds. */
    staleWhileRevalidateMs: 60 * 1000,
    /** Whether caching is enabled globally. */
    enabled: true,
  }),

  /**
   * SEO concerns.
   *
   * @type {{defaultTitle: string, titleTemplate: string, defaultDescription: string, defaultLocale: string, defaultOgType: string, robots: string, canonicalBase: string, keywords: string[]}}
   */
  seo: Object.freeze({
    /** Title used when a page does not specify one. */
    defaultTitle: 'Enterprise PSEO',
    /** Title template applied to every page; `%s` is replaced with the page title. */
    titleTemplate: '%s | Enterprise PSEO',
    /** Meta description used when a page does not specify one. */
    defaultDescription: 'Programmatic SEO pages generated by the Enterprise PSEO engine.',
    /** Default locale advertised in the document and Open Graph metadata. */
    defaultLocale: 'en_US',
    /** Default Open Graph object type. */
    defaultOgType: 'website',
    /** Default robots directive. */
    robots: 'index, follow',
    /** Base URL used to construct canonical links. */
    canonicalBase: 'https://example.com',
    /** Default keyword set appended when none is provided. */
    keywords: Object.freeze([]),
  }),

  /**
   * Logging concerns.
   *
   * @type {{level: string, format: string, colorize: boolean, timestamp: boolean}}
   */
  logging: Object.freeze({
    /** Minimum severity emitted. One of `debug`, `info`, `warn`, `error`. */
    level: 'info',
    /** Output format. One of `json`, `text`. */
    format: 'text',
    /** Whether to colorize text output for terminal display. */
    colorize: true,
    /** Whether to prepend an ISO timestamp to each log line. */
    timestamp: true,
  }),

  /**
   * Validation concerns.
   *
   * @type {{strict: boolean, throwOnInvalid: boolean, allowUnknownKeys: boolean, maxErrors: number}}
   */
  validation: Object.freeze({
    /** Whether to apply strict validation rules (reject unknown shapes). */
    strict: true,
    /** Whether to throw on validation failure instead of returning a result. */
    throwOnInvalid: false,
    /** Whether unknown keys are tolerated when strict mode is disabled. */
    allowUnknownKeys: false,
    /** Maximum number of validation errors collected before short-circuiting. */
    maxErrors: 50,
  }),
});
